"""Test cross-section computation against Fortran PC.f95 reference output.

Compares Python results at angles 0, 90, and 180 against every (E, Q1, Q2)
row in the Fortran PC.out.XXX files (generated by PC.f95 with accuracy=0.001,
emin=1e-9, emax=5e-4, nlong=4).

Also includes:
- turning-point regression check against the Fortran MINIM result for the
  angle=0 potential at E=1e-9, b=160.54817488594156;
- turning-point residual check that |E - V(r_m) - E*b^2/r_m^2| ~ 0 across a
  grid of (E, b) sample points (internal consistency, no Fortran involved);
- accuracy-convergence check that solving at accuracy=1e-3 vs 1e-4 moves
  Q^(1), Q^(2) by less than the looser run's stated accuracy (internal
  consistency, no Fortran involved);
- chi-independent check that solver.deflection_angle agrees with a from-
  scratch r-space recomputation that shares no change-of-variables with
  the production code (internal consistency, no Fortran involved);
- multi-orbit region count check against PC_mult_orb.in (must detect the
  4 disjoint orbiting energy regions Fortran finds).
"""

import numpy as np
from scipy.integrate import quad
from transport_from_potential import (
    read_single_potential, Potential,
    orbiting_scan, orbiting_regions, CrossSectionSolver,
)

TOLERANCE_PERCENT = 0.5


def read_pc_out(path):
    """Parse the cross-section table from a Fortran PC.out file.

    Returns a list of (E, Q1, Q2) tuples — one per energy block in the
    cross-section table.  The table follows the "orbiting energy regions"
    header and consists of repeated blocks of 1 energy + 30 Q^(ell) values
    (Q1..Q30), here truncated to Q1 and Q2.
    """
    in_table = False
    tokens = []
    with open(path) as f:
        for line in f:
            if "orbiting energy regions" in line:
                in_table = True
                continue
            if not in_table or "Region" in line:
                continue
            tokens.extend(line.split())

    floats = [float(t) for t in tokens]
    return [(floats[i], floats[i + 1], floats[i + 2])
            for i in range(0, len(floats), 31)]


def build_solver(angle, accuracy=0.001):
    data = np.loadtxt(f"data/PC.in.{angle:03d}", skiprows=1)
    distances = data[:, 0].tolist()
    energies = data[:, 1].tolist()

    pot = Potential(distances, energies, -4)
    clong = -energies[-1] * distances[-1]**4

    orbit_list, ED = orbiting_scan(pot, 1e-9, 4, clong)
    regions = orbiting_regions(orbit_list)
    solver = CrossSectionSolver(pot, orbit_list, regions, 4, clong, accuracy, ED=ED)
    return solver


def test_angle(angle):
    solver = build_solver(angle)
    reference = read_pc_out(f"data/PC.out.{angle:03d}")
    failures = 0
    worst_err = 0.0

    for E_test, q1_ref, q2_ref in reference:
        cs = solver.compute(E_test, 2)
        err1 = abs(cs[0] - q1_ref) / q1_ref * 100
        err2 = abs(cs[1] - q2_ref) / q2_ref * 100
        worst_err = max(worst_err, err1, err2)

        if err1 >= TOLERANCE_PERCENT or err2 >= TOLERANCE_PERCENT:
            failures += 1
            print(f"  [FAIL] E={E_test:.4e}  "
                  f"Q1={cs[0]:10.1f} (ref {q1_ref:10.1f}, err {err1:.2f}%)  "
                  f"Q2={cs[1]:10.1f} (ref {q2_ref:10.1f}, err {err2:.2f}%)")

    status = "PASS" if failures == 0 else "FAIL"
    print(f"  [{status}] {len(reference)} energies checked; worst err {worst_err:.2f}%")
    return failures


def test_turning_point():
    """Regression check: find_turning_point on angle=0 potential.

    Fortran MINIM (PC.f95) returns 5.8523768464909843 for E=1e-9,
    b=160.54817488594156.  Python is expected to agree to ~12 digits.
    """
    E = 1.0e-9
    b = 160.54817488594156
    R_M_EXPECTED = 5.852376846490984  # matches Fortran MINIM to ~17 digits
    TOLERANCE = 1.0e-10

    solver = build_solver(0)
    r_m, _ = solver.find_turning_point(E, b)
    err = abs(r_m - R_M_EXPECTED)
    status = "PASS" if err < TOLERANCE else "FAIL"
    print(f"  [{status}] r_m={r_m!r}  (expected {R_M_EXPECTED}, diff {err:.2e})")
    return 0 if status == "PASS" else 1


def test_turning_point_residual():
    """Internal consistency: |E - V(r_m) - E*b^2/r_m^2| ~ 0 at every r_m.

    Samples (E, b) across the physical range and checks that the turning
    point returned by find_turning_point actually satisfies its defining
    equation.  Independent of Fortran reference values.
    """
    TOLERANCE = 1.0e-10
    energies = [1e-9, 1e-8, 1e-7, 1e-6, 1e-5, 1e-4, 5e-4]
    b_values = [0.0, 1.0, 5.0, 20.0]

    solver = build_solver(0)
    max_residual = 0.0
    n_checks = 0
    for E in energies:
        for b in b_values:
            r_m, _ = solver.find_turning_point(E, b)
            V_rm = solver.pot(r_m)
            residual = abs(E - V_rm - E * b**2 / r_m**2)
            scale = max(abs(E), abs(V_rm))
            max_residual = max(max_residual, residual / scale)
            n_checks += 1

    status = "PASS" if max_residual < TOLERANCE else "FAIL"
    print(f"  [{status}] max relative residual = {max_residual:.2e} "
          f"over {n_checks} (E, b) points")
    return 0 if status == "PASS" else 1


def test_accuracy_convergence():
    """Tightening the accuracy knob must change Q^(1), Q^(2) by less than
    the looser run's stated accuracy.

    Internal consistency: if compute(E) at accuracy=A truly delivers an
    answer accurate to A, then rerunning at a tighter accuracy should move
    the result by less than A.  A failure here means the quadrature isn't
    actually converging at the requested accuracy.
    """
    A_LOOSE = 1.0e-3
    A_TIGHT = 1.0e-4
    # Sample low, mid, and high E in the input range.  At angle 0 the
    # orbiting region is [~8e-10, 3.5e-4], so 1e-9 is just below, 1e-6 is
    # well inside, and 5e-4 is just above.
    test_energies = [1.0e-9, 1.0e-6, 5.0e-4]

    solver_loose = build_solver(0, accuracy=A_LOOSE)
    solver_tight = build_solver(0, accuracy=A_TIGHT)

    failures = 0
    max_rel = 0.0
    for E in test_energies:
        cs_loose = solver_loose.compute(E, 2)
        cs_tight = solver_tight.compute(E, 2)
        for ell, (q_loose, q_tight) in enumerate(zip(cs_loose, cs_tight), 1):
            rel = abs(q_loose - q_tight) / abs(q_tight)
            max_rel = max(max_rel, rel)
            if rel >= A_LOOSE:
                failures += 1
                print(f"  [FAIL] E={E:.2e} Q^({ell})  "
                      f"loose={q_loose:.4f} tight={q_tight:.4f} "
                      f"rel diff={rel:.2e}")

    status = "PASS" if failures == 0 else "FAIL"
    print(f"  [{status}] max relative change = {max_rel:.2e} "
          f"(tolerance {A_LOOSE:.0e}); {len(test_energies) * 2} (E, ell) checks")
    return failures


def chi_independent(pot, r_m, E, b):
    """chi(E, b) via direct r-space integration with u = b/r substitution.

    chi = pi - 2 * integral_0^{u_max} du / sqrt(1 - u^2 - V(b/u)/E),
    with u_max = b/r_m.  The sqrt singularity at u = u_max is absorbed by
    a second substitution s = sqrt(u_max - u), making the integrand smooth
    at the endpoint.  Shares no change-of-variables or integrand with
    solver.deflection_angle.
    """
    u_max = b / r_m

    def integrand(s):
        u = u_max - s * s
        if u <= 0:
            return 0.0
        f = 1.0 - u * u - pot(b / u) / E
        if f <= 0:
            return 0.0
        return 2.0 * s / np.sqrt(f)

    result, _ = quad(integrand, 0.0, np.sqrt(u_max),
                     epsrel=1e-10, epsabs=1e-14)
    return np.pi - 2.0 * result


def test_chi_independent():
    """Internal consistency: production chi agrees with from-scratch chi.

    Catches bugs in the production change-of-variables and limit handling
    that the accuracy-convergence check can't, since both runs there share
    the same algorithm.
    """
    TOLERANCE = 1.0e-3  # production runs at accuracy=1e-3 by default

    solver = build_solver(0)
    # E > EC (~3.5e-4 at angle 0) so the qint code path sets naitk=0,
    # BO=[]; deflection_angle stays in case1 (single turning point) and
    # matches the production call signature.
    test_pairs = [(5.0e-4, 0.5), (5.0e-4, 5.0), (5.0e-4, 50.0)]

    failures = 0
    max_diff = 0.0
    for E, b in test_pairs:
        chi_prod = solver.deflection_angle(
            E, b, naitk=0, BO=[], RO=[], ROMAX=0.0)
        r_m, _ = solver.find_turning_point(E, b)
        chi_scratch = chi_independent(solver.pot, r_m, E, b)
        diff = abs(chi_prod - chi_scratch)
        max_diff = max(max_diff, diff)
        if diff > TOLERANCE:
            failures += 1
            print(f"  [FAIL] E={E:.2e} b={b}  prod={chi_prod:.8f}  "
                  f"indep={chi_scratch:.8f}  |diff|={diff:.2e}")

    status = "PASS" if failures == 0 else "FAIL"
    print(f"  [{status}] max |chi_prod - chi_indep| = {max_diff:.2e} rad "
          f"over {len(test_pairs)} (E, b) points")
    return failures


def test_mult_orb_regions():
    """Check that PC_mult_orb.in yields the 4 orbiting regions Fortran finds.

    Pre-rewrite, the algorithm collapsed all orbits into a single region;
    catching the count is the cheapest guard against that regression.  Also
    verify the orbit-list energy reaches ~1e-3, since the old bug truncated
    it at ~4e-4.
    """
    EXPECTED_REGIONS = 4
    MIN_TOP_ENERGY = 9.0e-4   # Fortran reaches ~1.004e-3; old bug stopped near 4e-4

    _, _, emin, _, nlong, distances, energies = \
        read_single_potential("data/PC_mult_orb.in")
    pot = Potential(distances, energies, -nlong)
    clong = -energies[-1] * distances[-1]**nlong
    orbit_list, _ = orbiting_scan(pot, emin, nlong, clong)
    regions = orbiting_regions(orbit_list)

    top_energy = max(r[1] for r in regions) if regions else 0.0
    count_ok = len(regions) == EXPECTED_REGIONS
    energy_ok = top_energy > MIN_TOP_ENERGY
    status = "PASS" if (count_ok and energy_ok) else "FAIL"
    print(f"  [{status}] regions={len(regions)} (expected {EXPECTED_REGIONS}), "
          f"top E={top_energy:.4e} (expected > {MIN_TOP_ENERGY:.0e})")
    return 0 if status == "PASS" else 1


if __name__ == "__main__":
    total_failures = 0
    for angle in [0, 90, 180]:
        print(f"Angle {angle}:")
        total_failures += test_angle(angle)
        print()

    print("Turning point (angle=0, E=1e-9, b=160.548...):")
    total_failures += test_turning_point()
    print()

    print("Turning-point residual (grid of E, b):")
    total_failures += test_turning_point_residual()
    print()

    print("Accuracy convergence (angle=0, accuracy 1e-3 vs 1e-4):")
    total_failures += test_accuracy_convergence()
    print()

    print("Independent chi recomputation (angle=0, E > EC):")
    total_failures += test_chi_independent()
    print()

    print("Multi-orbit regions (PC_mult_orb.in):")
    total_failures += test_mult_orb_regions()
    print()

    if total_failures == 0:
        print("All tests passed.")
    else:
        print(f"{total_failures} test(s) FAILED.")
        exit(1)
