"""Test cross-section computation against Fortran PC.f95 reference output.

Compares Python results at angles 0, 90, and 180 against values extracted
from the Fortran PC.out.XXX files (generated by PCforBMM with accuracy=0.001,
emin=1e-9, emax=5e-4, nlong=4).

Also includes:
- turning-point regression check against the Fortran MINIM result for the
  angle=0 potential at E=1e-9, b=160.54817488594156;
- multi-orbit region count check against PC_mult_orb.in (must detect the
  4 disjoint orbiting energy regions Fortran finds).
"""

import numpy as np
from transport_from_potential import (
    read_single_potential, Potential,
    orbiting_scan, orbiting_regions, CrossSectionSolver,
)

# Reference values: (energy, Q1_fortran, Q2_fortran)
# extracted from PC.out.000, PC.out.090, PC.out.180
REFERENCE_DATA = {
    0: [
        (1.0000e-09, 178223.8, 124228.7),
        (0.59005386880730261e-06, 7082.455, 5157.486),
        (0.50000000000000000e-03, 243.5134, 212.3188),
    ],
    90: [
        (1.0000e-09, 175642.0, 123097.1),
        (0.68327390405862076e-08, 66969.98, 47131.83),
        (0.70710678118654752e-06, 6441.861, 4659.225),
        (0.73177095895221403e-04, 624.7279, 475.5057),
    ],
    180: [
        (1.0000e-09, 172612.5, 121184.5),
        (0.65653823010457322e-08, 67087.38, 47314.01),
        (0.61702142504208522e-06, 6745.450, 4891.665),
    ],
}

TOLERANCE_PERCENT = 0.5


def build_solver(angle):
    data = np.loadtxt(f"data/PC.in.{angle:03d}", skiprows=1)
    distances = data[:, 0].tolist()
    energies = data[:, 1].tolist()

    pot = Potential(distances, energies, -4)
    clong = -energies[-1] * distances[-1]**4

    orbit_list, ED = orbiting_scan(pot, 1e-9, 4, clong)
    regions = orbiting_regions(orbit_list)
    solver = CrossSectionSolver(pot, orbit_list, regions, 4, clong, 0.001, ED=ED)
    return solver


def test_angle(angle):
    solver = build_solver(angle)
    failures = 0

    for E_test, q1_ref, q2_ref in REFERENCE_DATA[angle]:
        cs = solver.compute(E_test, 2)
        err1 = abs(cs[0] - q1_ref) / q1_ref * 100
        err2 = abs(cs[1] - q2_ref) / q2_ref * 100

        status = "PASS" if err1 < TOLERANCE_PERCENT and err2 < TOLERANCE_PERCENT else "FAIL"
        if status == "FAIL":
            failures += 1

        print(f"  [{status}] E={E_test:.4e}  "
              f"Q1={cs[0]:10.1f} (ref {q1_ref:10.1f}, err {err1:.2f}%)  "
              f"Q2={cs[1]:10.1f} (ref {q2_ref:10.1f}, err {err2:.2f}%)")

    return failures


def test_turning_point():
    """Regression check: find_turning_point on angle=0 potential.

    Fortran MINIM (PC.f95) returns 5.8523768464909843 for E=1e-9,
    b=160.54817488594156.  Python is expected to agree to ~12 digits.
    """
    E = 1.0e-9
    b = 160.54817488594156
    R_M_EXPECTED = 5.852376846490984  # matches Fortran MINIM to ~17 digits
    TOLERANCE = 1.0e-10

    solver = build_solver(0)
    r_m, _ = solver.find_turning_point(E, b)
    err = abs(r_m - R_M_EXPECTED)
    status = "PASS" if err < TOLERANCE else "FAIL"
    print(f"  [{status}] r_m={r_m!r}  (expected {R_M_EXPECTED}, diff {err:.2e})")
    return 0 if status == "PASS" else 1


def test_mult_orb_regions():
    """Check that PC_mult_orb.in yields the 4 orbiting regions Fortran finds.

    Pre-rewrite, the algorithm collapsed all orbits into a single region;
    catching the count is the cheapest guard against that regression.  Also
    verify the orbit-list energy reaches ~1e-3, since the old bug truncated
    it at ~4e-4.
    """
    EXPECTED_REGIONS = 4
    MIN_TOP_ENERGY = 9.0e-4   # Fortran reaches ~1.004e-3; old bug stopped near 4e-4

    _, _, emin, _, nlong, distances, energies = \
        read_single_potential("data/PC_mult_orb.in")
    pot = Potential(distances, energies, -nlong)
    clong = -energies[-1] * distances[-1]**nlong
    orbit_list, _ = orbiting_scan(pot, emin, nlong, clong)
    regions = orbiting_regions(orbit_list)

    top_energy = max(r[1] for r in regions) if regions else 0.0
    count_ok = len(regions) == EXPECTED_REGIONS
    energy_ok = top_energy > MIN_TOP_ENERGY
    status = "PASS" if (count_ok and energy_ok) else "FAIL"
    print(f"  [{status}] regions={len(regions)} (expected {EXPECTED_REGIONS}), "
          f"top E={top_energy:.4e} (expected > {MIN_TOP_ENERGY:.0e})")
    return 0 if status == "PASS" else 1


if __name__ == "__main__":
    total_failures = 0
    for angle in [0, 90, 180]:
        print(f"Angle {angle}:")
        total_failures += test_angle(angle)
        print()

    print("Turning point (angle=0, E=1e-9, b=160.548...):")
    total_failures += test_turning_point()
    print()

    print("Multi-orbit regions (PC_mult_orb.in):")
    total_failures += test_mult_orb_regions()
    print()

    if total_failures == 0:
        print("All tests passed.")
    else:
        print(f"{total_failures} test(s) FAILED.")
        exit(1)
