"""Test cross-section computation against Fortran PC.f95 reference output.

Compares Python results at angles 0, 90, and 180 against values extracted
from the Fortran PC.out.XXX files (generated by PCforBMM with accuracy=0.001,
emin=1e-9, emax=5e-4, nlong=4).
"""

import numpy as np
from transport_from_potential import (
    Potential, orbiting_scan, orbiting_regions, CrossSectionSolver
)

# Reference values: (energy, Q1_fortran, Q2_fortran)
# extracted from PC.out.000, PC.out.090, PC.out.180
REFERENCE_DATA = {
    0: [
        (1.0000e-09, 178223.8, 124228.7),
        (0.59005386880730261e-06, 7082.455, 5157.486),
        (0.50000000000000000e-03, 243.5134, 212.3188),
    ],
    90: [
        (1.0000e-09, 175642.0, 123097.1),
        (0.68327390405862076e-08, 66969.98, 47131.83),
        (0.70710678118654752e-06, 6441.861, 4659.225),
        (0.73177095895221403e-04, 624.7279, 475.5057),
    ],
    180: [
        (1.0000e-09, 172612.5, 121184.5),
        (0.65653823010457322e-08, 67087.38, 47314.01),
        (0.61702142504208522e-06, 6745.450, 4891.665),
    ],
}

TOLERANCE_PERCENT = 0.5


def build_solver(angle):
    data = np.loadtxt(f"PC.in.{angle:03d}", skiprows=1)
    distances = data[:, 0].tolist()
    energies = data[:, 1].tolist()

    pot = Potential(distances, energies, -4)
    clong = -energies[-1] * distances[-1]**4

    orbit_list, ED = orbiting_scan(pot, 1e-9, 4, clong)
    regions = orbiting_regions(orbit_list)
    solver = CrossSectionSolver(pot, orbit_list, regions, 4, clong, 0.001)
    solver.ED = ED
    return solver


def test_angle(angle):
    solver = build_solver(angle)
    failures = 0

    for E_test, q1_ref, q2_ref in REFERENCE_DATA[angle]:
        cs = solver.compute(E_test, 2)
        err1 = abs(cs[0] - q1_ref) / q1_ref * 100
        err2 = abs(cs[1] - q2_ref) / q2_ref * 100

        status = "PASS" if err1 < TOLERANCE_PERCENT and err2 < TOLERANCE_PERCENT else "FAIL"
        if status == "FAIL":
            failures += 1

        print(f"  [{status}] E={E_test:.4e}  "
              f"Q1={cs[0]:10.1f} (ref {q1_ref:10.1f}, err {err1:.2f}%)  "
              f"Q2={cs[1]:10.1f} (ref {q2_ref:10.1f}, err {err2:.2f}%)")

    return failures


if __name__ == "__main__":
    total_failures = 0
    for angle in [0, 90, 180]:
        print(f"Angle {angle}:")
        total_failures += test_angle(angle)
        print()

    if total_failures == 0:
        print("All tests passed.")
    else:
        print(f"{total_failures} test(s) FAILED.")
        exit(1)
